# Generated by Django 2.2.3 on 2019-08-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190806_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.FileField(upload_to='contents/'),
        ),
    ]
