# Generated by Django 2.2.3 on 2019-08-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190806_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='farther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category'),
        ),
    ]
