# Generated by Django 2.2.3 on 2019-08-06 11:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190806_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '手册', 'verbose_name_plural': '手册'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': '目录', 'verbose_name_plural': '目录'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-pub_date'], 'verbose_name': '手册内容', 'verbose_name_plural': '手册内容'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AddField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=70, verbose_name='手册'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Tag', verbose_name='标签(可为空)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book', verbose_name='所属手册'),
        ),
        migrations.AlterField(
            model_name='category',
            name='farther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category', verbose_name='上一级目录(可为空)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=70, verbose_name='目录名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(verbose_name='排列顺序-升序'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='所属目录'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='手册内容'),
        ),
        migrations.AlterField(
            model_name='content',
            name='headline',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
