# Generated by Django 2.2.3 on 2019-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190806_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default='', null=True, upload_to='media/cover_img/', verbose_name='封面图片'),
        ),
    ]
