# Generated by Django 2.2.3 on 2019-08-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190813_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'permissions': [('valid', '可以审核')], 'verbose_name': '目录', 'verbose_name_plural': '目录'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_valid',
            field=models.IntegerField(choices=[(1, '审核通过'), (0, '未审核')], default=0, verbose_name='是否审核通过'),
        ),
    ]
