# Generated by Django 2.2.3 on 2019-08-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190813_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'permissions': [('valid_category', '可以审核')], 'verbose_name': '目录', 'verbose_name_plural': '目录'},
        ),
    ]
