# Generated by Django 2.2.3 on 2019-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190813_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排列顺序-升序'),
        ),
    ]
