# Generated by Django 2.2.3 on 2019-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_content_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='', null=True, upload_to='icon/', verbose_name='目录图标'),
        ),
    ]
